### PR TITLE
Readme vamp

### PR DESCRIPTION
**Pull request by Styrle**

### CODE REVIEW

**Comment by Shankhanil** [comment]
I will review this ASAP. I apologize for the delay @Styrle  Thank you for the contribution!

**Comment by Shankhanil** [comment]
@Styrle can you please create a PR and include your name in the contributor's list?

**Comment by Styrle** [comment]
Yeah sure

**Comment by Styrle** [comment]
@Shankhanil Also could you possibly send me some examples of a good PR in which I could look at for some context

**Pull request merged**
